### ISSUE TITLE
关于桥的tproxy

### ISSUE THREAD

**Issue by ploynomail** [owent-utils/docker-setup#1]
我在参考：https://github.com/owent-utils/docker-setup/blob/main/setup-router/v2ray/setup-tproxy.nft.sh
的时候发现：
nft add rule bridge v2ray PREROUTING meta pkttype set unicast # ether daddr set 00:00:00:00:00:0

**Comment by ploynomail** [comment]
> 我在参考：https://github.com/owent-utils/docker-setup/blob/main/setup-router/v2ray/setup-tproxy.nft.sh
> 的时候发现：
> nft add rule bridge v2ray PREROUTING meta pkttype set unicast # ether daddr set 00:00:00:00:00:0

这个配置并没有生效，流量依然从网桥forward了。
是否我哪里没有配置正确。

**Comment by owent** [comment]
> 
> 
> > 我在参考：https://github.com/owent-utils/docker-setup/blob/main/setup-router/v2ray/setup-tproxy.nft.sh
> > 的时候发现：
> > nft add rule bridge v2ray PREROUTING meta pkttype set unicast # ether daddr set 00:00:00:00:00:0
> 
> 这个配置并没有生效，流量依然从网桥forward了。
> 是否我哪里没有配置正确。

@cyrus-zhang  我这里只是留着官方文档的写法。但是nftables目前并不支持BROUTE的DROP哈。详见 https://www.mankier.com/8/ebtables-nft#Bugs
我家里还是用得ebtables管理的网桥

**Comment by ploynomail** [comment]
> > > 我在参考：https://github.com/owent-utils/docker-setup/blob/main/setup-router/v2ray/setup-tproxy.nft.sh
> > > 的时候发现：
> > > nft add rule bridge v2ray PREROUTING meta pkttype set unicast # ether daddr set 00:00:00:00:00:0
> > 
> > 
> > 这个配置并没有生效，流量依然从网桥forward了。
> > 是否我哪里没有配置正确。
> 
> @cyrus-zhang 我这里只是留着官方文档的写法。但是nftables目前并不支持BROUTE的DROP哈。详见 https://www.mankier.com/8/ebtables-nft#Bugs
> 我家里还是用得ebtables管理的网桥

这个问题我想办法解决了：
nft add rule bridge v2ray PREROUTING meta pkttype set unicast # ether daddr set xx:xx:xx:xx:xx #这里填写bridge mac就可以

但是我遇到了新的问题，bridge的prerouteing已经接收到了tcp，udp流量，并且mark已经成功，但是策略路由并没有其作用，而是把流量递交给了input hook，input的流量中已经有了正确mark值(例外的是，在桥所在的主机上面往外访问tcp，udp 可以成功的被策略路由 路由到lo上面)，我不知道桥接网卡和ip rule fwmark直接是不是有什么配置。

下面是我在ip prerouting和input两个地方进行trace 的结果，prerouting 上面看起来正常，mark已经成功，但是没有被策略路由捕获：
trace id 571a68da ip STU PREROUTING packet: iif "br0" ether saddr a2:e4:d9:4b:f5:e2 ether daddr 8a:8c:1e:8c:0d:97 ip saddr 172.16.99.102 ip daddr 112.80.248.75 ip dscp cs0 ip ecn not-ect ip ttl 64 ip id 57340 ip length 60 tcp sport 34673 tcp dport 80 tcp flags == syn tcp window 29200 
trace id 571a68da ip STU PREROUTING rule tcp dport { 80 } meta nftrace set 1 (verdict continue)
trace id 571a68da ip STU PREROUTING rule meta mark & 0x0000000f != 0x0000000e meta l4proto { tcp, udp } meta mark set meta mark & 0xfffffffe | 0x0000000e (verdict continue)
trace id 571a68da ip STU PREROUTING rule ct mark set meta mark & 0x0000ffff (verdict continue)
trace id 571a68da ip STU PREROUTING verdict continue meta mark 0x0000000e 
trace id 571a68da ip STU PREROUTING policy accept meta mark 0x0000000e 
trace id d0d2d063 ip STU INPUT packet: iif "br0" ether saddr a2:e4:d9:4b:f5:e2 ether daddr 8a:8c:1e:8c:0d:97 ip saddr 172.16.99.102 ip daddr 112.80.248.75 ip dscp cs0 ip ecn not-ect ip ttl 64 ip id 57340 ip length 60 tcp sport 34673 tcp dport 80 tcp flags == syn tcp window 29200 
trace id d0d2d063 ip STU INPUT rule tcp dport { 80 } meta nftrace set 1 (verdict continue)
trace id d0d2d063 ip STU INPUT verdict continue meta mark 0x0000000e 
trace id d0d2d063 ip STU INPUT policy accept meta mark 0x0000000e 


如果你碰到过累死的情况帮哥们一把，卡了好几天了。

**Comment by owent** [comment]
看 https://www.mankier.com/8/ebtables-legacy#Description-Targets 和 https://inai.de/images/nf-packet-flow.svg 这个图。
![图片](https://user-images.githubusercontent.com/1209475/121312345-dd699300-c937-11eb-90c8-b417e8a08f7e.png)

网桥走的是最下面那条流程，必须在 `BROUTING` 阶段 `DROP` 掉。才会往上走，不然整个流程里是没有 `routingdecision` 的。策略路由也就自然没用了。

**Comment by ploynomail** [comment]
> 看 https://www.mankier.com/8/ebtables-legacy#Description-Targets 和 https://inai.de/images/nf-packet-flow.svg 这个图。
> ![图片](https://user-images.githubusercontent.com/1209475/121312345-dd699300-c937-11eb-90c8-b417e8a08f7e.png)
> 
> 网桥走的是最下面那条流程，必须在 `BROUTING` 阶段 `DROP` 掉。才会往上走，不然整个流程里是没有 `routingdecision` 的。策略路由也就自然没用了。


现在bridge流量已经到了ip层并且已经呗prerouting 捕获 mark了标签， 但是该标签好像被策略路由忽律。下面是我的nft配置：


table ip STU { # handle 1
        set BLACKLIST { # handle 1
                type ipv4_addr
        }

        set GEOIP_CN { # handle 2
                type ipv4_addr
                flags interval
        }

        set GEOIP_HK { # handle 3
                type ipv4_addr
                flags interval
        }

        chain INPUT { # handle 57
                type filter hook input priority filter + 2; policy accept;
                tcp dport { 80 } meta nftrace set 1 # handle 59
        }

        chain PREROUTING { # handle 70
                type filter hook prerouting priority mangle; policy accept;
                ip saddr { 39.109.117.106 } return # handle 72
                meta l4proto != { tcp, udp } return # handle 74
                tcp sport { 22 } return # handle 76
                udp sport { 22 } return # handle 78
                udp dport { 53, 67, 123 } return # handle 80
                ip daddr { 127.0.0.1, 224.0.0.0/4, 255.255.255.255 } return # handle 82
                meta mark & 0x00000070 == 0x00000070 return # handle 83
                ip daddr { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 } return # handle 85
                ip daddr { 119.29.29.29, 180.76.76.76, 223.5.5.5, 223.6.6.6 } return # handle 87
                ip daddr @BLACKLIST return # handle 88
                ip daddr @GEOIP_CN return # handle 89
                meta mark & 0x0000000f != 0x0000000e meta l4proto { tcp, udp } meta mark set meta mark & 0xfffffffe | 0x0000000e # handle 91
                ct mark set meta mark & 0x0000ffff # handle 92
                meta l4proto tcp tproxy to :1080 accept # handle 93
                meta l4proto udp tproxy to :1080 accept # handle 94
        }

        chain OUTPUT { # handle 95
                type route hook output priority filter + 1; policy accept;
                meta l4proto != { tcp, udp } return # handle 97
                tcp sport { 22 } return # handle 99
                udp sport { 22 } return # handle 101
                udp dport { 53, 67, 123 } return # handle 103
                ip daddr { 39.109.117.106 } return # handle 105
                ip daddr { 127.0.0.1, 224.0.0.0/4, 255.255.255.255 } return # handle 107
                ip daddr { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 } return # handle 109
                ip daddr { 119.29.29.29, 180.76.76.76, 223.5.5.5, 223.6.6.6 } return # handle 111
                meta mark & 0x00000070 == 0x00000070 return # handle 112
                meta mark & 0x0000000f != 0x0000000e meta l4proto { tcp, udp } meta mark set meta mark & 0xfffffffe | 0x0000000e return # handle 114
                ct mark set meta mark & 0x0000ffff # handle 115
        }
}
table bridge STU { # handle 2
        chain PREROUTING { # handle 16
                type filter hook prerouting priority dstnat + 1; policy accept;
                arp ptype ip return # handle 18
                meta l4proto != { tcp, udp } return # handle 20
                udp dport { 53, 67, 123 } return # handle 22
                meta mark & 0x00000070 == 0x00000070 return # handle 23
                ip daddr { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 } return # handle 25
                ip daddr { 119.29.29.29, 180.76.76.76, 223.5.5.5, 223.6.6.6 } return # handle 27
                meta pkttype set host ether daddr set 8a:8c:1e:8c:0d:97 # handle 28
        }

        chain FORWARD { # handle 17
                type filter hook forward priority -298; policy accept;
        }
}

root@FriendlyELEC:~/tproxy# ip rule list
0:      from all lookup local
17995:  from all fwmark 0xe/0xf lookup 100
32766:  from all lookup main
32767:  from all lookup default


root@FriendlyELEC:~/tproxy# sysctl -p
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.br0.rp_filter = 0
net.ipv4.conf.eth0.rp_filter = 0
net.ipv4.conf.eth1.rp_filter = 0
net.ipv4.ip_nonlocal_bind = 1
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
net.bridge.bridge-nf-call-ip6tables = 0
net.bridge.bridge-nf-call-iptables = 0
net.bridge.bridge-nf-call-arptables = 0

上面是我的配置


在ip STU的input 我已经看到了我的流量。

很感谢能这么及时回复。

**Comment by ploynomail** [comment]
root@FriendlyELEC:~# ip route get 112.80.248.75 from 172.16.99.102 iif eth1 mark 0xe
local 112.80.248.75 from 172.16.99.102 dev lo table 100 mark 14 
    cache <local> iif eth1 
root@FriendlyELEC:~# ip route get 112.80.248.75 from 172.16.99.102 iif eth0 mark 0xe
local 112.80.248.75 from 172.16.99.102 dev lo table 100 mark 14 
    cache <local> iif eth0 
root@FriendlyELEC:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master br0 state UP group default qlen 1000
    link/ether 8a:8c:1e:8c:0d:97 brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 state UP group default qlen 1000
    link/ether 8a:8c:bb:0a:06:0c brd ff:ff:ff:ff:ff:ff
4: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 8a:8c:1e:8c:0d:97 brd ff:ff:ff:ff:ff:ff
    inet 172.16.99.100/24 brd 172.16.99.255 scope global dynamic br0
       valid_lft 6518sec preferred_lft 6518sec
    inet6 fe80::888c:1eff:fe8c:d97/64 scope link 
       valid_lft forever preferred_lft forever

补充一下网络环境

**Comment by owent** [comment]
下面的流程图里也是有 `PREROUTING` 的

**Comment by ploynomail** [comment]
刚才打开追踪，发现TRACE里面有比较详细的内容， 
mangle:PREROUTING: 已经mark了 标签，但就是不能被策略路由使用。

Jun  9 08:42:57 FriendlyELEC kernel: [ 9019.290843] TRACE: mangle:PREROUTING:policy:1 IN=br0 OUT= MAC=8a:8c:1e:8c:0d:97:a2:e4:d9:4b:f5:e2:08:00 SRC=172.16.99.102 DST=112.80.248.76 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=1047 DF PROTO=TCP SPT=46137 DPT=80 SEQ=1182424269 ACK=0 WINDOW=29200 RES=0x00 SYN URGP=0 OPT (020405B40402080A00A6593F0000000001030306) MARK=0xe 
Jun  9 08:42:57 FriendlyELEC kernel: [ 9019.290989] TRACE: mangle:INPUT:policy:1 IN=br0 OUT= MAC=8a:8c:1e:8c:0d:97:a2:e4:d9:4b:f5:e2:08:00 SRC=172.16.99.102 DST=112.80.248.76 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=1047 DF PROTO=TCP SPT=46137 DPT=80 SEQ=1182424269 ACK=0 WINDOW=29200 RES=0x00 SYN URGP=0 OPT (020405B40402080A00A6593F0000000001030306) MARK=0xe 
Jun  9 08:42:59 FriendlyELEC kernel: [ 9021.290761] TRACE: mangle:PREROUTING:policy:1 IN=br0 OUT= MAC=8a:8c:1e:8c:0d:97:a2:e4:d9:4b:f5:e2:08:00 SRC=172.16.99.102 DST=112.80.248.76 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=1048 DF PROTO=TCP SPT=46137 DPT=80 SEQ=1182424269 ACK=0 WINDOW=29200 RES=0x00 SYN URGP=0 OPT (020405B40402080A00A65A070000000001030306) MARK=0xe 
Jun  9 08:42:59 FriendlyELEC kernel: [ 9021.290900] TRACE: mangle:INPUT:policy:1 IN=br0 OUT= MAC=8a:8c:1e:8c:0d:97:a2:e4:d9:4b:f5:e2:08:00 SRC=172.16.99.102 DST=112.80.248.76 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=1048 DF PROTO=TCP SPT=46137 DPT=80 SEQ=1182424269 ACK=0 WINDOW=29200 RES=0x00 SYN URGP=0 OPT (020405B40402080A00A65A070000000001030306) MARK=0xe

**Comment by owent** [comment]
我比你多一个 `net.ipv4.conf.br0.route_localnet=1`  其他都差不多一样的。看上面的图，bridge流程里也是有ip的 `PREROUTING` 的。但是没有 `routing decision` 。

**Comment by owent** [comment]
http://ebtables.netfilter.org/br_fw_ia/br_fw_ia.pdf 和 https://www.mankier.com/8/ebtables-legacy#Description-Targets 
这两个文档都是说 `BROUTE` 是一个特殊的chain。只有在这里才能决定一个包是走路由还是走桥接。

**Comment by ploynomail** [comment]
感谢你的回答，上面的问题已经解决了。

**Comment by ploynomail** [comment]
老板让我基于上述的理论做一个透明的网关，桥上不能配置ip(至少不能手工或者dhcp)，要让机器像一根网线一样来使用。但是我还没有想到什么好的办法。

**Comment by owent** [comment]
没看懂，啥叫透明网关呀？感觉DHCP对网桥下发网关的ip不就可以插上网线自动设置网络了吗？和tproxy也没啥关系？
如果是说透明代理的话，倒是可以用tproxy。把网关的流量代理了就行了。我家里就是代理路由器网关的流量的，不过涉及桥接的部分我是直接用的ebtables，没用nftables

**Comment by ploynomail** [comment]
> 没看懂，啥叫透明网关呀？感觉DHCP对网桥下发网关的ip不就可以插上网线自动设置网络了吗？和tproxy也没啥关系？
> 如果是说透明代理的话，倒是可以用tproxy。把网关的流量代理了就行了。我家里就是代理路由器网关的流量的，不过涉及桥接的部分我是直接用的ebtables，没用nftables

好的谢谢了。 很感谢你的回答。
